 const baseFolder = '/flags'

 const countryInfo = [
    {name: 'Argentina',
    countryCode: '+54',
    flag: `${baseFolder}/ar.svg`,
    },
    {name: 'Bolivia',
    countryCode: '+591',
    flag: `${baseFolder}/bo.png`,
    },
    {name: 'Brasil',
    countryCode: '+55',
    flag: `${baseFolder}/br.png`,
    },
    {name: 'Chile',
    countryCode: '+56',
    flag: `${baseFolder}/cl.png`,
    },
    {name: 'Colombia',
    countryCode: '+57',
    flag: `${baseFolder}/co.png`,
    },
    {name: 'España',
    countryCode: '+34',
    flag: `${baseFolder}/es.png`,
    },
    {name: 'Perú',
    countryCode: '+51',
    flag: `${baseFolder}/pe.png`,
    },
    {name: 'Paraguay',
    countryCode: '+595',
    flag: `${baseFolder}/py.png`,
    },
    {name: 'Uruguay',
    countryCode: '+598',
    flag: `${baseFolder}/uy.png`,
    },
    {name: 'Venezuela',
    countryCode: '+58',
    flag: `${baseFolder}/ve.png`,
    },
    {name: 'Ecuador',
    countryCode: '+593',
    flag: `${baseFolder}/ec.png`,
    },
]

export default countryInfo;